import { createHash } from 'node:crypto';
import { parseCmsSourceDocuments } from '../../src/content/contracts/source';
import type { CmsPayload } from '../../src/content/contracts/registry';
import { stableCompactStringify, stableStringify } from './json';
import { buildSourceDocuments } from './extract';
import type { GeneratedArtifacts, SourceDocument } from './types';

const PUBLISHED_AT = '2026-08-14T00:00:00.000Z';

type SnapshotRow = {
  readonly document_id: string;
  readonly kind: SourceDocument['kind'];
  readonly stable_key: string;
  readonly revision_id: string;
  readonly version: 1;
  readonly payload: CmsPayload;
  readonly published_at: string;
};

function deterministicUuid(namespace: 'document' | 'revision', document: SourceDocument): string {
  const hex = createHash('sha256')
    .update(`tmuh-mededu-cms:${namespace}:${document.kind}:${document.stableKey}`)
    .digest('hex');
  const variant = namespace === 'document' ? '8' : '9';
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-5${hex.slice(13, 16)}-${variant}${hex.slice(17, 20)}-${hex.slice(20, 32)}`;
}

function snapshotRow(document: SourceDocument): SnapshotRow {
  return {
    document_id: deterministicUuid('document', document),
    kind: document.kind,
    stable_key: document.stableKey,
    revision_id: deterministicUuid('revision', document),
    version: 1,
    payload: document.payload,
    published_at: PUBLISHED_AT,
  };
}

function sqlLiteral(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function renderSql(rows: readonly SnapshotRow[]): string {
  const documents = rows
    .map(
      (row) =>
        `  (${sqlLiteral(row.document_id)}, ${sqlLiteral(row.kind)}, ${sqlLiteral(row.stable_key)})`,
    )
    .join(',\n');
  const revisions = rows
    .map(
      (row) =>
        `  (${sqlLiteral(row.revision_id)}, ${sqlLiteral(row.document_id)}, 1, 'published', ${sqlLiteral(stableCompactStringify(row.payload))}::jsonb, ${sqlLiteral(row.published_at)}::timestamptz)`,
    )
    .join(',\n');

  return `-- Generated by npm run content:generate. Do not edit by hand.\n\ninsert into public.cms_documents (id, kind, stable_key)\nvalues\n${documents};\n\ninsert into public.cms_revisions (id, document_id, version, status, payload, published_at)\nvalues\n${revisions};\n`;
}

export function buildArtifacts(input: unknown = buildSourceDocuments()): GeneratedArtifacts {
  const rows = parseCmsSourceDocuments(input).map(snapshotRow);
  return {
    snapshot: stableStringify(rows),
    sql: renderSql(rows),
  };
}
